version: '3.4'

services:
    phonebookdb: 
        container_name: phonebookdb
        restart: always
        ports:
            - "27017:27017"

    phonebook.api:
        container_name: phonebookapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "PhonebookDatabaseSettings:ConnectionString=mongodb://phonebookdb:27017"
        depends_on:
            - phonebookdb
        ports:
            - "8000:80"
