version: '3.4'

services:
    phonebookdb: 
        container_name: phonebookdb
        restart: always
        ports:
            - "27017:27017"

    rabbitmq: 
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"

    phonebook.api:
        container_name: phonebookapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "PhonebookDatabaseSettings:ConnectionString=mongodb://phonebookdb:27017"
            - "EventBus:HostName=rabbitmq"
        depends_on:
            - phonebookdb
            - rabbitmq
        ports:
            - "8000:80"

    report.api:
        container_name: reportapi
        restart: "on-failure"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "PhonebookDatabaseSettings:ConnectionString=mongodb://phonebookdb:27017"
            - "EventBus:HostName=rabbitmq"
        depends_on:
            - phonebookdb
            - rabbitmq
        ports:
           - "80001:80"

