version: '3.4'

services:
    phonebookdb:
        image: mongo
    rabbitmq:
        image: rabbitmq:3-management

    phonebook.api:
        image: ${DOCKER_REGISTRY-}phonebookapi
        build:
            context: .
            dockerfile: src/Phonebook/Phonebook.API/Dockerfile

    report.api:
        image: ${DOCKER_REGISTRY-}reportapi
        build:
            context: .
            dockerfile: src/Report/Report.API/Dockerfile

